---
azcli_base_url: https://packages.microsoft.com
azcli_gpg_key: "{{ azcli_base_url }}/keys/microsoft.asc"
azcli_arch: amd64
azcli_release_channel: main

azcli_repo_url: "{{ azcli_base_url }}/repos/azure-cli/"
azcli_repository: "deb [arch={{ azcli_arch }}] {{ azcli_repo_url }} {{ ansible_distribution_release }} {{ azcli_release_channel }}"
azcli_keyid: BC528686B50D79E339D3721CEB3E94ADBE1229CF

azcli_prereq_packages: ["ca-certificates", "curl", "apt-transport-https", "lsb-release", "gnupg"]
